### ISSUE TITLE
Trouble building web/ember

### ISSUE THREAD

**Issue by ericf89** [themroberts/emberjs-bowling-app#1]
Hey there! 

I'm trying to get your web code built/served to try things out, but `ember serve` spits out the following.  

```
Build failed.
File: bowling/models/frame.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: bowling/models/frame.js: Unexpected token (39:55)

    // Allow shot2 to have Strike denoted if last frame
    if((frame_index === 9) && (this.get('hit_strike')) {
      return "X";
    }

    at Parser.pp.raise (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseParenExpression (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:440:8)
    at Parser.pp.parseIfStatement (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:267:20)
    at Parser.pp.parseStatement (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:87:19)
    at Parser.pp.parseBlock (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.pp.parseFunction (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:524:8)
    at Parser.pp.parseExprAtom (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:397:19)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:39:10)
    at new Babel (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/emberjs-bowling-app/web/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/emberjs-bowling-app/web/node_modules/ember-cli-babel/index.js:21:52)
    at /emberjs-bowling-app/web/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/emberjs-bowling-app/web/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessJs (/emberjs-bowling-app/web/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at EmberApp.appAndDependencies (/emberjs-bowling-app/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1044:25)
```

Any thoughts?

**Comment by themroberts** [comment]
Hi. The if statement is missing its closing parenthesis. The fix has been pushed to master and will now work for you. Thanks.
